# No [graph] all-features: this crate declares no features of its own, and
# auditing ratatui's optional termwiz/termina backends (WTFPL terminfo,
# Unicode-DFS wezterm-bidi) would fail the license check for code we never ship.
[advisories]
yanked = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
